### ISSUE TITLE
The name of this repository

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc-pac#1]
Thanks for creating this repository, @rnestler! Since you didn't leave any work for me, I figured I'd get in on some bikeshedding :)

I'd prefer it if this repository was just called lpc-pac, for two reasons:
- I think the current name with the two dashes looks a bit noisy. `lpc-pac` would be easier to parse.
- There's already an `-rs` in the organization name, so having it again in the repository name is redundant.

I don't feel that strongly though, so if any of you disagree, feel free to close this issue.

**Comment by dbrgn** [comment]
I'd +1 on that one :slightly_smiling_face: It's kind of redundant when the organization name already contains `-rs`.

**Comment by hannobraun** [comment]
Any objections, @rnestler? If not, I'm happy to rename it (well, not like that's too much work :) ).

**Comment by rnestler** [comment]
> Any objections, @rnestler? If not, I'm happy to rename it (well, not like that's too much work :) ).

No real objections, I just prefer repository names to be meaningful themselves without the organization name, because when I do a git clone it doesn't create a folder with the organization name, but just the repository. 

Edit: So go ahead and rename it, since @dbrgn and you already have the majority vote :wink:

**Comment by dbrgn** [comment]
I think "lpc-pac" is already quite meaningful :slightly_smiling_face:

**Comment by rnestler** [comment]
Done.

**Comment by hannobraun** [comment]
Thanks, @rnestler! As a note, you can rename or move your local repository in any way you like. Personally, I prefer to sort them into folders based on organization (at least on my work machine, where I have way too many local repositories :) ).
