### ISSUE TITLE
SVD file contains duplicate names

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc-pac#14]
Original issue: https://github.com/lpc-rs/lpc82x-pac/issues/6

---

The SVD file contains duplicate names that prevent the generated code from being compiled. We address this in [this patch](https://github.com/braun-robotics/rust-lpc82x/blob/9ec3157dae457b0dfc971cca1f1e87fd0a7e930c/LPC82x.svd.duplicate-names.patch), but ideally this should be fixed upstream.

I plan to contact NXP about this, but haven't gotten to it yet.

---

I've reported the issue to NXP: https://community.nxp.com/thread/465465

**Comment by dbrgn** [comment]
Yep. At first I was surprised to see that you got a response from NXP. But then I saw that the last response was from December 2017, that's more in line what I expected :confused: 

Their way of generating these SVD files is flawed. We either have to get them to fix that issue, or have to fix SVD files ourselves.

**Comment by hannobraun** [comment]
They've silently updated the SVD files since then. You can always get the latest version via the MCUXpresso SDK builder: https://mcuxpresso.nxp.com/en/welcome

The new version does indeed fix all the issues I reported, but introduce so many new ones that I've decided to stay with the old file. Reported here: https://community.nxp.com/thread/484757

**Comment by dbrgn** [comment]
:woman_facepalming:

**Comment by dbrgn** [comment]
Isn't providing SVD files a requirement for licensing ARM IP? Is there some kind of process to file a complaint?

**Comment by hannobraun** [comment]
> Isn't providing SVD files a requirement for licensing ARM IP? Is there some kind of process to file a complaint?

I don't know. First time I heard of that. In any case, I don't think a complaint is the right thing to do for now. I'm going to check if there are new versions soon, and if there aren't, I'm going to ask again in my post. If that doesn't result in anything, I'm going to write to a contact I have at NXP.

I think we should make it clear that this is a problem for us, but I don't think antagonizing them with a complaint (if such a thing is feasible) is going to be productive.

**Comment by dbrgn** [comment]
Yes, if we can get through to some of the engineers without a complaint, then that is definitely the better way :slightly_smiling_face:

**Comment by hannobraun** [comment]
Last time I talked to them about the topic, they were receptive, although I got the feeling that it's not their highest priority. I think gentle, but insistent nudging (via personal contacts, at events like Embedded World, and their forum) is going to be the best way.

**Comment by dbrgn** [comment]
@rnestler you said that you might attend Embedded World too, right? you could also ask them about those SVD files.
