### ISSUE TITLE
Integrate lpc82x-pac

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc-pac#2]
I've moved [lpc82x-pac](https://github.com/lpc-rs/lpc82x-pac) into this organization, but I've not integrated it into this repository yet. @rnestler, you mentioned that you moved the other PAC crates here with all their history. Could you do the same for lpc82x-pac?

If it's too much of a hassle, don't bother. I can either figure out how to do it myself, or just copy lpc82x-pac here without the history. Please let me know what you think.

**Comment by rnestler** [comment]
> Could you do the same for lpc82x-pac?

Sure thing :+1: I'll try to do it tonight. @dbrgn Please remind me :wink:

**Comment by dbrgn** [comment]
I'll try :slightly_smiling_face: 

We could also try updating lpc11uxx to the latest svd2rust master tonight.

**Comment by rnestler** [comment]
For reference:
```
git remote add lpc82x git@github.com:lpc-rs/lpc82x-pac.git
git fetch lpc82x
git checkout lpc82x lpc82x/master
mkdir lpc82x
git ls-tree -z --name-only HEAD | xargs -0 -I {} git mv {} lpc82x
git commit -m "Move everything into lpc82x subdirectory"
git checkout master
git merge  --allow-unrelated-histories  lpc82x
```

**Comment by rnestler** [comment]
Done.

**Comment by hannobraun** [comment]
Thank you!
