### ISSUE TITLE
Report lpc845 issues to NXP

### ISSUE THREAD

**Issue by hannobraun** [lpc-rs/lpc-pac#28]
cc @david-sawatzke

**Comment by david-sawatzke** [comment]
I've invited you as a participant.

I listed you as "Hanno" "Braun" "Braun Robotics" "hanno@braun-robotics.com", hope that's ok

**Comment by hannobraun** [comment]
That's perfect, thank you!

**Comment by david-sawatzke** [comment]
The nxp engineer said these issues would be fixed in the next release

**Comment by hannobraun** [comment]
General note: NXP has been very responsive to SVD issues recently. LPC82x issues have also been fixed and will be in the next release, according to the engineer that did it.

The trick seems to be to file a support ticket. Posting in the community forum doesn't hurt, but doesn't seem to be a sure way to get it done.

**Comment by dbrgn** [comment]
Nice!

@rnestler mabe you can open a support ticket with the LPC11Uxx fixes? (We should probably create a list of the problems we found.)

But that should probably be discussed in a separate ticket.
