### ISSUE TITLE
Use a workspace?

### ISSUE THREAD

**Issue by axos88** [lpc-rs/lpc-pac#36]
https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/cargo-workspaces-for-multi-package-projects.html

**Comment by hannobraun** [comment]
What would the benefit of a workspace be? I don't think it's even possible to build them together, as the different crates target different architectures (ARMv6-M and ARMv7-M).

I might be missing something though!

**Comment by dbrgn** [comment]
I also don't think that a workspace makes sense in this case.

I'll close the PR for now, feel free to add a comment with more context if there's a good reason to use a workspace, @axos88!
