### ISSUE TITLE
track merging onf lpc81x

### ISSUE THREAD

**Issue by allexoll** [lpc-rs/lpc-pac#76]
after discussing it in #75 , we might be able to include the lpc81x pac in here. 

there is a lot of differences between the patched 0.2 SVD (0.3? xml says 0.2), and the v1 SVD that is currently in this repository. 

As I don't have a board with that MCU, it would be hard to test, and to see what would need to be fixed for a new version of the lpc81x-hal crate as well. @apparentlymart seems to be the owner of the HAL. 

I don't think this would be an issue since both the PAC and the HAL have not been updated for a long time (3 and 2 years respectively). current new LPC pacs are on version 0.2.1, so they would not break current version of the hal, which relies on lpc-81x v0.1.0.

if @lucab is fine with moving the lpc81x pac here, that can be done by just publishing the current release (v0.2.1) that is generated by the current files for LPC81x. 

- [ ] publish lpc81x-hal crate

**Comment by lucab** [comment]
:+1:
Who should I add as an owner of the `lpc81x-pac` crate?

**Comment by allexoll** [comment]
as you want, either you stay sole owner of the pac crate, but that means that every time there is a new version, you would need to publish it, or you add me as an owner, and I do the publish everytime there is a new version.

**Comment by apparentlymart** [comment]
Hello!

I built lpc81x-hal as part of a specific project and haven't ended up using that platform for subsequent projects and so haven't had reason to work on it further. I believe I do still have at least one development board with an LPC812 chip in my lab somewhere, which I could potentially use for some testing if it's still functional.

I expect I'll have only limited time to maintain the HAL crate moving forward and so I would be happy to collaborate with others on it if anyone is interested. I must admit that I don't have the details of this platform at the front of my mind right now so I can't comment on the potential impacts of upgrading the PAC, but I'd be willing to give it a try if I can find my dev board.

**Comment by lucab** [comment]
In order to increase the bus-factor, I've invited @allexoll as an owner of `lpc81x-pac`. Feel free to directly publish new versions there.
I've also tried adding the https://crates.io/teams/github:lpc-rs:lpc8xx team, but `cargo` failed to do so (maybe because the team is private on GitHub or does not exist anymore?).

**Comment by allexoll** [comment]
thanks! I've published the new version, no idea about the lpc-rs team on crates.io, maybe @hannobraun has more insight?

**Comment by hannobraun** [comment]
I don't know what the problem could be. The team definitely exists and is set to "visible".
